from __future__ import annotations


STATE_META: dict[str, dict[str, str]] = {
    "AL": {"name": "Alabama", "blurb": "Rocket City energy, Gulf Coast breeze, and markets that move with quiet confidence."},
    "AK": {"name": "Alaska", "blurb": "Big distance, big scenery, and housing patterns shaped by pure frontier logic."},
    "AZ": {"name": "Arizona", "blurb": "Desert light, mountain edges, and fast-growing metros with real heat behind them."},
    "AR": {"name": "Arkansas", "blurb": "Ozark calm, Delta depth, and markets that feel steadier than they look."},
    "CA": {"name": "California", "blurb": "Coastline glamour, inland scale, and housing stories that never stay small."},
    "CO": {"name": "Colorado", "blurb": "High-altitude growth, trail-town appeal, and metros that keep climbing."},
    "CT": {"name": "Connecticut", "blurb": "Old-money shoreline, commuter grit, and compact markets with sharp price signals."},
    "DE": {"name": "Delaware", "blurb": "Small-state speed, beach pull, and a housing map that rewards close reading."},
    "FL": {"name": "Florida", "blurb": "Sunbelt momentum, coastal demand, and price action that can turn fast."},
    "GA": {"name": "Georgia", "blurb": "Atlanta gravity, Southern polish, and markets with serious range."},
    "HI": {"name": "Hawaii", "blurb": "Island scarcity, oceanfront pressure, and housing dynamics unlike anywhere else."},
    "ID": {"name": "Idaho", "blurb": "Mountain air, migration fuel, and markets that still know how to surprise."},
    "IL": {"name": "Illinois", "blurb": "Chicago muscle, prairie spread, and a statewide picture with real contrast."},
    "IN": {"name": "Indiana", "blurb": "Crossroads practicality, college-town sparks, and solid Midwestern price rhythm."},
    "IA": {"name": "Iowa", "blurb": "Corn-belt steadiness, underrated cities, and housing data with clean lines."},
    "KS": {"name": "Kansas", "blurb": "Big sky, balanced metros, and a market that rewards patience over hype."},
    "KY": {"name": "Kentucky", "blurb": "Horse country elegance, river-city pull, and markets with deep local texture."},
    "LA": {"name": "Louisiana", "blurb": "Cultural gravity, Gulf humidity, and housing moves with unmistakable flavor."},
    "ME": {"name": "Maine", "blurb": "Rocky coast, pine quiet, and demand that hits harder than the map suggests."},
    "MD": {"name": "Maryland", "blurb": "Beltway power, harbor edge, and some of the East Coast's sharpest local splits."},
    "MA": {"name": "Massachusetts", "blurb": "Academic gravity, old-stock housing, and markets with serious intensity."},
    "MI": {"name": "Michigan", "blurb": "Great Lakes scale, manufacturing legacy, and markets writing a new chapter."},
    "MN": {"name": "Minnesota", "blurb": "North Star order, lake-country calm, and metros with disciplined growth."},
    "MS": {"name": "Mississippi", "blurb": "Delta roots, Gulf access, and housing data that moves on local terms."},
    "MO": {"name": "Missouri", "blurb": "Gateway ambition, Ozark depth, and price patterns that bridge regions."},
    "MT": {"name": "Montana", "blurb": "Wide-open country, high-demand mountain towns, and markets with sharp edges."},
    "NE": {"name": "Nebraska", "blurb": "Plains pragmatism, strong regional hubs, and housing data without much noise."},
    "NV": {"name": "Nevada", "blurb": "Casino glare, desert expansion, and price cycles that know drama."},
    "NH": {"name": "New Hampshire", "blurb": "Granite steadiness, tax advantage, and demand that leaks north with purpose."},
    "NJ": {"name": "New Jersey", "blurb": "Shoreline pull, commuter muscle, and dense local markets with fast reads."},
    "NM": {"name": "New Mexico", "blurb": "Adobe light, mountain horizons, and markets with a slower, distinct pulse."},
    "NY": {"name": "New York", "blurb": "City-state gravity, upstate spread, and housing stories stacked in layers."},
    "NC": {"name": "North Carolina", "blurb": "Research Triangle momentum, mountain escapes, and one of the South's busiest housing maps."},
    "ND": {"name": "North Dakota", "blurb": "Energy-country toughness, open land, and small markets with clear signals."},
    "OH": {"name": "Ohio", "blurb": "Rust Belt reinvention, affordable depth, and metros full of movement."},
    "OK": {"name": "Oklahoma", "blurb": "Windy plains, fast-growing hubs, and practical markets with room to move."},
    "OR": {"name": "Oregon", "blurb": "Rain-soaked cool, high-desert reach, and a market split between calm and pressure."},
    "PA": {"name": "Pennsylvania", "blurb": "Historic cities, mountain corridors, and housing trends with real breadth."},
    "RI": {"name": "Rhode Island", "blurb": "Tiny footprint, salt-air appeal, and compact markets with punch."},
    "SC": {"name": "South Carolina", "blurb": "Lowcountry shine, inland growth, and housing demand with beach-town swagger."},
    "SD": {"name": "South Dakota", "blurb": "Prairie clarity, Black Hills draw, and markets that stay straightforward."},
    "TN": {"name": "Tennessee", "blurb": "Music-city magnetism, mountain reach, and growth that keeps finding new lanes."},
    "TX": {"name": "Texas", "blurb": "Massive metros, energy-state scale, and housing data that never lacks velocity."},
    "UT": {"name": "Utah", "blurb": "Mountain polish, tech-corridor momentum, and markets tuned for expansion."},
    "VT": {"name": "Vermont", "blurb": "Green Mountain calm, village-scale charm, and scarcity that quietly matters."},
    "VA": {"name": "Virginia", "blurb": "Capitol orbit, coastal range, and a housing map with both power and poise."},
    "WA": {"name": "Washington", "blurb": "Puget tech gravity, evergreen calm, and markets shaped by altitude and income."},
    "WV": {"name": "West Virginia", "blurb": "Mountain resilience, low-key towns, and housing patterns with their own cadence."},
    "WI": {"name": "Wisconsin", "blurb": "Lakefront industry, college-town lift, and solid price action across the map."},
    "WY": {"name": "Wyoming", "blurb": "Ranchland scale, energy-country economics, and housing signals with lots of sky around them."},
}


def get_state_meta(state_code: str) -> dict[str, str]:
    code = (state_code or "").upper()
    return STATE_META.get(code, {"name": code or "State", "blurb": "A quick read on local housing movement."})
